services:
  
  db:
    image: postgres:16
    container_name: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - 5432
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    env_file:
      - .env
    ports:
      - 6379:6379

volumes:
  pg-data:
  redis-data:
